services:
  backend:
    build: ./backend
    container_name: ra-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - YOLO_MODEL_REF=yolov8n.pt
    volumes:
      - ./backend:/app
      - ./data:/data        # zajednički storage mount
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    container_name: ra-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000   # nije presudno za prod build, ali ostavi
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy

  worker:
    build: ./worker
    container_name: ra-worker
    environment:
      - BACKEND_URL=http://backend:8000
      - UPLOADS_DIR=/data/uploads
      - RESULTS_DIR=/data/results
      - PROCESSED_DIR=/data/processed
      - FAILED_DIR=/data/failed
      - YOLO_MODEL_REF=yolov8n.pt
    volumes:
      - ./worker:/worker
      - ./data:/data        # isti volumen da worker vidi uploadane fajlove
    depends_on:
      backend:
        condition: service_started
