services:
  backend:
    image: ghcr.io/hfenda/retail-analytics/backend:${IMAGE_TAG:-main}
    pull_policy: always
    container_name: ra-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - YOLO_MODEL_REF=yolov8n.pt
      - PYTHONPATH=/app:/ml
    volumes:
      - ./data:/data
      - ./ml:/ml:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/openapi.json"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    container_name: ra-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy

  worker:
    image: ghcr.io/hfenda/retail-analytics/worker:${IMAGE_TAG:-main}
    pull_policy: always
    container_name: ra-worker
    environment:
      - BACKEND_URL=http://backend:8000
      - UPLOADS_DIR=/data/uploads
      - RESULTS_DIR=/data/results
      - PROCESSED_DIR=/data/processed
      - FAILED_DIR=/data/failed
      - YOLO_MODEL_REF=yolov8n.pt
    volumes:
      - ./data:/data
    depends_on:
      backend:
        condition: service_started
