name: Build & Push frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yml"
  workflow_dispatch: {}

concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_BASENAME: retail-analytics-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set OWNER_LC
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Compose IMAGE (lowercase)
        run: echo "IMAGE=${REGISTRY}/${OWNER_LC}/${IMAGE_BASENAME}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER_LC }}
          # Može i: password: ${{ secrets.GITHUB_TOKEN }} (ako Actions imaju Write packages)
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.FRONTEND_API_BASE_URL }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
          tags: |
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:sha-${{ github.sha }}
