name: CI Frontend

on:
  workflow_dispatch:
  push:
    paths: ["frontend/**", ".github/workflows/ci-frontend.yml"]
  pull_request:
    paths: ["frontend/**"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install
        run: npm ci --prefix frontend

      - name: Lint
        run: npm run lint --prefix frontend || true

      - name: Build
        env:
          NEXT_PUBLIC_API_BASE: "http://localhost:8000"
          NODE_OPTIONS: "--max-old-space-size=3072"
        run: npm run build --prefix frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/.next
