name: Build & Push worker

on:
  push:
    branches: [ "main" ]
    paths:
      - "worker/**"
      - "ml/**"
      - "backend/app/**"
      - ".github/workflows/ci-worker.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_BASENAME: retail-analytics-worker

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Compose image
        run: echo "IMAGE=${REGISTRY}/${OWNER_LC}/${IMAGE_BASENAME}" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .                # ROOT, da vidi ml/ i backend/app/
          file: worker/Dockerfile   # Dockerfile u worker/
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:sha-${{ github.sha }}
