name: CI Worker

on:
  push:
    paths:
      - "worker/**"
      - "ml/**"
      - ".github/workflows/ci-worker.yml"
  pull_request:
    paths:
      - "worker/**"
      - "ml/**"
      - ".github/workflows/ci-worker.yml"
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-worker-${{ hashFiles('worker/requirements.txt', 'ml/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-worker-

      - name: Install deps
        working-directory: worker
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # opcionalno:
          pip install pytest

      - name: Unit tests
        working-directory: worker
        run: |
          pytest -q || true

      - name: Static build check
        run: |
          FILES="$(git ls-files 'worker/**/*.py' 'ml/**/*.py' || true)"
          if [ -n "$FILES" ]; then
            python -m py_compile $FILES
          else
            echo "No Python files to compile in worker/ml."
          fi