name: Deploy Worker to Heroku
on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'
      - 'ml/**'
      - 'backend/app/**'
      - '.github/workflows/deploy-heroku-worker.yml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_APP: ra-worker
      HEROKU_REG: registry.heroku.com
      IMAGE: registry.heroku.com/ra-worker/worker
    steps:
      - uses: actions/checkout@v4

      - name: Login to Heroku Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login -u _ -p "${{ secrets.HEROKU_API_KEY }}" $HEROKU_REG

      - name: Build (amd64)
        run: docker build --platform=linux/amd64 -t $IMAGE -f worker/Dockerfile .

      - name: Push
        run: docker push $IMAGE

      - name: Release
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/${{ env.HEROKU_APP }}/formation \
           -d '{
                 "updates": [
                   {
                     "type": "worker",
                     "docker_image": "'"$(docker inspect $IMAGE --format={{.Id}})"'"
                   }
                 ]
               }' \
           -H "Content-Type: application/json" \
           -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
           -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}"
